name: flutter_udid
description: Plugin to retrieve a persistent UDID across reinstalls on iOS and Android
version: 3.0.0
homepage: https://github.com/GigaDroid/flutter_udid

environment:
  sdk: ">=2.18.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: de.gigadroid.flutter_udid
        pluginClass: FlutterUdidPlugin
      ios:
        pluginClass: FlutterUdidPlugin
      macos:
        pluginClass: FlutterUdidPlugin
      windows:
        pluginClass: FlutterUdidPluginCApi
      linux:
        pluginClass: FlutterUdidPlugin